import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import App from "./App";

const state = {
  contract_version: "v0.6c-unified-runtime-v1",
  system: { status: "PASS_FAIL_CLOSED_NO_CHAMPION", mode: "SHADOW_ADVISORY_ONLY", symbol: "EURUSD", generated_time: { utc: "2026-08-24T12:00:00Z", asia_colombo: "2026-08-24T17:30:00+05:30" }, registry: { champion_count: 0 } },
  market: { close: 1.166, freshness: { status: "FRESH" }, session: "OVERLAP" },
  predictions: { v06a_status: "PASS_SHADOW_RUNNING", horizons: { "15": { model_status: "NO_APPROVED_MODEL", model_id: null, prob_down: null, prob_neutral: null, prob_up: null, decision_gate: "WAIT_NO_MODEL" }, "60": { model_status: "NO_APPROVED_MODEL", model_id: null, prob_down: null, prob_neutral: null, prob_up: null, decision_gate: "WAIT_NO_MODEL" }, "240": { model_status: "NO_APPROVED_MODEL", model_id: null, prob_down: null, prob_neutral: null, prob_up: null, decision_gate: "WAIT_NO_MODEL" } }, fusion: { status: "NO_APPROVED_MODEL", direction: "WAIT", confidence: "VERY_LOW", probabilities: null, valid_horizons: [] } },
  decision: { action: "WAIT", direction: "WAIT", action_meaning: "No directional advice is available.", confidence: "VERY_LOW", gate: "WAIT_NO_MODEL", manual_confirmation_required: true, trading_enabled: false, decision_time: { utc: "2026-08-24T11:55:00Z", asia_colombo: null }, next_reassessment: { utc: "2026-08-24T12:05:00Z", asia_colombo: null } },
  trade_window: { status: "NOT_APPLICABLE_WAIT", start_utc: null, end_utc: null }, event: { status: "NONE" }, intelligence: { status: "DEGRADED" }, health: { sources: { v05a_market: "PASS", v05b_intelligence: "PASS_DEGRADED" }, failed_sources: [], degraded_sources: [] }, reasons: [{ code: "NO_APPROVED_MODEL", priority: 95, blocking: true, source: "V0.5C", message: "No approved V0.5C champion", evidence: null }]
};
const operator = { contract_version: "v0.7", current_time: { utc: "2026-08-24T12:00:00Z", asia_colombo: "2026-08-24T17:30:00+05:30" }, market: { status: "OPEN", market_open: true, reason: "OPEN", next_market_open_utc: null, next_market_close_utc: "2026-08-28T21:00:00Z" }, session: { current_session: "LONDON + NEW YORK", active_sessions: ["LONDON", "NEW_YORK"], overlap: true, next_session: "SYDNEY", next_session_change_utc: "2026-08-24T16:00:00Z", next_transition: "NEW YORK CLOSE" }, data_freshness: { status: "FRESH", reason: "FRESH", basis: "FEATURE_ROW", latest_market_tick_utc: "2026-08-24T11:59:58Z", latest_completed_m5_utc: "2026-08-24T11:55:00Z", latest_completed_m15_utc: "2026-08-24T11:45:00Z", feature_row_utc: "2026-08-24T11:58:00Z", market_age_seconds: 120, tick_age_seconds: 2, m5_age_seconds: 300, m15_age_seconds: 900, feature_age_seconds: 120, market_closed_context: false }, reassessment: { status: "SCHEDULED", at_utc: "2026-08-24T12:05:00Z", reason: "V06_NEXT_REASSESSMENT" }, trading_window: { status: "WAITING_FOR_MODEL", reason: "NO_APPROVED_MODEL", trading_state: "WAIT", execution: "DISABLED", trading_enabled: false, manual_confirmation_required: true }, system_health: { status: "PASS", reason: "HEALTHY" }, trading_state: "WAIT", wait_explanation: "Waiting for an approved model before a directional advisory can be published.", runtime_gate: "WAIT_NO_MODEL", mode: "SHADOW_ADVISORY_ONLY" };

function response(data: unknown) { return Promise.resolve({ ok: true, status: 200, json: () => Promise.resolve(data), headers: new Headers({ "X-MarketFusion-State-Freshness": "FRESH" }) } as Response); }
function mockFetch() { vi.stubGlobal("fetch", vi.fn((input: RequestInfo | URL) => { const url = String(input); const path = url.split("?")[0]; if (path === "/api/state") return response(state); if (path === "/api/operator/status") return response(operator); if (path === "/api/market/candles") return response({ status: "PASS", timeframe: "M5", count: 0, candles: [] }); if (path === "/api/market/summary") return response({ status: "PASS_RUNNING", bid: 1.16, ask: 1.17, mid: 1.165, spread_points: 1 }); if (path === "/api/engines/status") return response({ status: "PASS", contract_version: "v0.9a", engines: {}, external_engines: {}, observational_only: true, v06_integration: false }); if (path === "/api/evaluation/shadow/summary") return response({ status: "NO_LIVE_SHADOW_OBSERVATIONS_YET", recorder: { status: "RUNNING", last_cycle_reason: "MARKET_CLOSED_WEEKEND" }, performance_observations: 0, total_observations: 0, counts: {}, horizons: {} }); if (path === "/api/evaluation/shadow/recent") return response({ items: [] }); if (path === "/api/v08/status") return response({}); if (path === "/api/events") return response({ events: [] }); if (path === "/api/intelligence") return response({ status: "DEGRADED", news_counts: {}, macro: {}, provider_health: {} }); return response({ candidates: {}, approved_champions: 0 }); })); }
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });

describe("redesigned dashboard", () => {
  it("shows the overview decision and command bar", async () => { mockFetch(); render(<App />); expect(await screen.findByText("Current Advisory")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Overview" })).toHaveClass("active"); expect(screen.getByText("SHADOW / MANUAL")).toBeInTheDocument(); });
  it("supports the six navigation tabs", async () => { mockFetch(); render(<App />); expect(await screen.findByRole("button", { name: "Market" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Models" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Engines" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Validation" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "System" })).toBeInTheDocument(); });
  it("expands actual WAIT reasons", async () => { mockFetch(); render(<App />); await screen.findByText("No directional advice is available."); screen.getByRole("button", { name: "WHY WAIT?" }).click(); await waitFor(() => expect(screen.getByText("No approved V0.5C champion")).toBeInTheDocument()); expect(screen.getAllByText("NO APPROVED MODEL").length).toBeGreaterThan(0); });
  it("keeps model details behind the Models tab", async () => { mockFetch(); render(<App />); screen.getByRole("button", { name: "Models" }).click(); expect(await screen.findByText("Model Status")).toBeInTheDocument(); expect(screen.getAllByText("NO APPROVED MODEL").length).toBeGreaterThanOrEqual(3); });
  it("keeps validation behind the Validation tab", async () => { mockFetch(); render(<App />); screen.getByRole("button", { name: "Validation" }).click(); expect(await screen.findByText("Validation")).toBeInTheDocument(); expect(screen.getByText("NO LIVE SHADOW OBSERVATIONS YET")).toBeInTheDocument(); });
  it("offers safe refresh and diagnostics actions", async () => { mockFetch(); render(<App />); expect(await screen.findByRole("button", { name: "REFRESH" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "DIAGNOSTICS" })).toBeInTheDocument(); expect(screen.queryByRole("button", { name: /BUY|SELL|ORDER|EXECUTE/i })).not.toBeInTheDocument(); });
  it("switches every read-only API group to XAUUSD without showing model probabilities", async () => { mockFetch(); render(<App />); const selector = await screen.findByRole("combobox", { name: "Asset" }); fireEvent.change(selector, { target: { value: "XAUUSD" } }); await waitFor(() => expect(vi.mocked(fetch).mock.calls.some(([input]) => String(input) === "/api/state?symbol=XAUUSD")).toBe(true)); const urls = vi.mocked(fetch).mock.calls.map(([input]) => String(input)); expect(urls).toContain("/api/market/summary?symbol=XAUUSD"); expect(urls).toContain("/api/engines/status?symbol=XAUUSD"); expect(screen.getByText("PRECIOUS METAL")).toBeInTheDocument(); expect(screen.getAllByText("NO APPROVED MODEL").length).toBeGreaterThan(0); });
});
